- hosts: citadel487-bot
  become: true
  become_method: sudo

  vars:
    app_docker_image: "{{ lookup('ansible.builtin.env', 'APP_DOCKER_IMAGE') }}"
    docker_yandex_cloud_login: true
    publish_app_ports: false
    add_mongo: false
    project_path: /opt/citadel487-bot
    project_environment:
      - DEPLOY_TYPE=prod

  roles:
    - docker-compose-project
